# Generated by Django 3.2 on 2024-06-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='お問合せ日時')),
                ('content', models.TextField(verbose_name='お問合せ内容')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('corporate_name', models.CharField(max_length=30, verbose_name='企業名')),
                ('pic_name', models.CharField(max_length=30, verbose_name='担当者名')),
                ('phonenumber', models.CharField(max_length=16, verbose_name='電話番号')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='お問合せ日時')),
                ('content', models.TextField(verbose_name='お問合せ内容')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('fullname', models.CharField(max_length=30, verbose_name='氏名')),
                ('kana', models.CharField(max_length=60, verbose_name='フリガナ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
